version: '2'

#here we create the volumes. We keep the same names for backup purposes
volumes:
  homebridge:
    name: homebridge
  homeassistant:
    name: homeassistant

services:
#Homebridge allows you to integrate with smart home devices that do not natively support HomeKit.
  homebridge:
    env_file: ./hmsc-apps/env/smarthome.env
    container_name: homebridge
    image: oznu/homebridge:latest
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - homebridge:/homebridge
    network_mode: host
    restart: always
#AirConnect: It allows you to be able to use AirPlay to push audio to Chromecast and UPNP based devices.
  airconnect:
    env_file: ./hmsc-apps/env/smarthome.env
    container_name: airconnect
    image: 1activegeek/airconnect
    network_mode: host
    restart: unless-stopped
#Home Assistant - Open source home automation that puts local control and privacy first.
  homeassistant:
    env_file: ./hmsc-apps/env/smarthome.env
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - privileged
    volumes:
      - homeassistant:/config
    network_mode: host
    restart: always